language: ruby
rvm:
  - 2.4.0
services:
  - postgresql
addons:
  code_climate:
    repo_token: d76dac93c914d616d4a86129945e56358fcc2cfa81d3938cfa7b0981ea11d9ba

before_script:
  - psql -c "create database gimail_test;" -U postgres
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
